export type ProjectCategory = "Full-Stack" | "Frontend" | "Backend" | "AI/ML" | "Mobile";

export interface ProjectTechnology {
  name: string;
  color: string; // bg-color-500
}

export interface Project {
  id: string;
  title: string;
  description: string;
  longDescription: string;
  category: ProjectCategory;
  image: string;
  images?: string[]; // Additional screenshots
  technologies: ProjectTechnology[];
  features: string[];
  challengesSolved: string[];
  github?: string;
  liveDemo?: string;
  startDate: string;
  endDate: string;
  status: "Completed" | "In Progress" | "Planned";
  featured?: boolean;
}

export const projectsData: Project[] = [
  {
    id: "1",
    title: "TrackTaxi - Taxi Service Platform",
    description: "Full-stack taxi booking platform with real-time tracking and payment integration",
    longDescription:
      "A comprehensive taxi service platform built during internship at The Reciprocal Solutions. Collaborated on GitHub with PRs and conflict resolution, deployed with Docker, Kafka, and ClickHouse for real-time data processing.",
    category: "Full-Stack",
    image: "/images/projects/tracktaxi.jpg",
    images: [
      "/images/projects/tracktaxi.jpg",
      "/images/projects/tracktaxi-2.jpg",
    ],
    technologies: [
      { name: "Next.js (TSX)", color: "bg-black" },
      { name: "Node.js", color: "bg-green-500" },
      { name: "Docker", color: "bg-blue-500" },
      { name: "Kafka", color: "bg-gray-700" },
      { name: "ClickHouse", color: "bg-yellow-500" },
      { name: "GitHub", color: "bg-gray-800" },
    ],
    features: [
      "Real-time taxi tracking and booking",
      "Deployed with Docker containerization",
      "Kafka integration for message streaming",
      "ClickHouse for data analytics",
      "GitHub collaboration with PRs and conflict resolution",
      "Production-ready deployment",
    ],
    challengesSolved: [
      "Implemented real-time data processing with Kafka",
      "Optimized database queries with ClickHouse",
      "Managed GitHub PRs and resolved merge conflicts",
      "Deployed scalable application with Docker",
    ],
    liveDemo: "https://tracktaxi.in/",
    startDate: "Jul 2024",
    endDate: "Present",
    status: "Completed",
    featured: true,
  },
  {
    id: "2",
    title: "Sado Taxi - Taxi Service Platform",
    description: "Taxi booking platform with OTP verification and email/Telegram integrations",
    longDescription:
      "A taxi service platform with integrated OTP verification, email services, and Telegram bot integration. Improved booking logic and user experience with real-time notifications.",
    category: "Full-Stack",
    image: "/images/projects/sado-taxi.jpg",
    images: [
      "/images/projects/sado-taxi.jpg",
      "/images/projects/sado-taxi-2.jpg",
    ],
    technologies: [
      { name: "Next.js", color: "bg-black" },
      { name: "Node.js", color: "bg-green-500" },
      { name: "MongoDB", color: "bg-green-600" },
      { name: "Telegram API", color: "bg-blue-400" },
      { name: "Email Services", color: "bg-red-500" },
    ],
    features: [
      "OTP verification for secure authentication",
      "Email notification system",
      "Telegram bot integration for updates",
      "Improved booking logic and workflow",
      "Real-time notifications",
      "User-friendly interface",
    ],
    challengesSolved: [
      "Integrated multiple third-party services (OTP, Email, Telegram)",
      "Built secure authentication with OTP verification",
      "Optimized booking workflow for better UX",
      "Implemented real-time notification system",
    ],
    liveDemo: "https://sado-taxi.onrender.com/",
    startDate: "Jul 2024",
    endDate: "Aug 2024",
    status: "Completed",
    featured: true,
  },
  {
    id: "3",
    title: "Balaji Dharsan AD Travels",
    description: "Mobile-optimized travel booking platform with pricing and itinerary management",
    longDescription:
      "A production travel website specially made for mobile devices. Improved pricing modules, itinerary handling, and booking logic for seamless travel booking experience.",
    category: "Full-Stack",
    image: "/images/projects/balaji-travels.jpg",
    images: [
      "/images/projects/balaji-travels.jpg",
      "/images/projects/balaji-travels-2.jpg",
    ],
    technologies: [
      { name: "Next.js", color: "bg-black" },
      { name: "React", color: "bg-cyan-500" },
      { name: "Node.js", color: "bg-green-500" },
      { name: "MongoDB", color: "bg-green-600" },
      { name: "Mobile-First", color: "bg-purple-500" },
    ],
    features: [
      "Mobile-first responsive design",
      "Advanced pricing modules",
      "Itinerary handling and management",
      "Booking workflow optimization",
      "Production-ready deployment",
      "Seamless user experience",
    ],
    challengesSolved: [
      "Built mobile-optimized UI for better engagement",
      "Implemented complex pricing calculation logic",
      "Created intuitive itinerary management system",
      "Optimized booking flow for conversion",
    ],
    liveDemo: "https://balajidharsantravels.com/one-day",
    startDate: "Jul 2024",
    endDate: "Aug 2024",
    status: "Completed",
    featured: false,
  },
  {
    id: "4",
    title: "MERN Currency Converter",
    description: "Full-stack currency conversion app with real-time exchange rates",
    longDescription:
      "Developed a full-stack application with real-time currency conversion using exchange rate APIs. Built with the MERN stack for fast and responsive user experience.",
    category: "Full-Stack",
    image: "/images/projects/currency-converter.jpg",
    technologies: [
      { name: "MongoDB", color: "bg-green-600" },
      { name: "Express.js", color: "bg-gray-700" },
      { name: "React", color: "bg-cyan-500" },
      { name: "Node.js", color: "bg-green-500" },
      { name: "Exchange Rate API", color: "bg-blue-500" },
    ],
    features: [
      "Real-time currency conversion",
      "Integration with exchange rate APIs",
      "Clean and intuitive UI",
      "Fast and responsive",
      "Multiple currency support",
      "Historical rate tracking",
    ],
    challengesSolved: [
      "Integrated real-time exchange rate API",
      "Implemented efficient data caching",
      "Created responsive UI with React",
      "Optimized API calls for performance",
    ],
    liveDemo: "https://currencyconvetoriyaps.netlify.app/",
    startDate: "Mar 2024",
    endDate: "Apr 2024",
    status: "Completed",
    featured: false,
  },
  {
    id: "5",
    title: "Detecting Emotion Through Eye Analysis",
    description: "MATLAB and Deep Learning project for emotion detection using EEG and eye movement",
    longDescription:
      "Created EmotionMeter, a multimodal deep learning system combining EEG and eye movement data. Achieved 88.57% accuracy in classifying emotions using advanced machine learning techniques.",
    category: "AI/ML",
    image: "/images/projects/emotion-detection.jpg",
    technologies: [
      { name: "MATLAB", color: "bg-orange-500" },
      { name: "Deep Learning", color: "bg-purple-600" },
      { name: "EEG Analysis", color: "bg-blue-600" },
      { name: "Eye Tracking", color: "bg-green-500" },
      { name: "ML Models", color: "bg-pink-500" },
    ],
    features: [
      "Multimodal emotion detection system",
      "EEG and eye movement data analysis",
      "Deep learning model with 88.57% accuracy",
      "Real-time emotion classification",
      "Advanced data preprocessing",
      "Academic research project",
    ],
    challengesSolved: [
      "Combined multiple data sources (EEG + eye tracking)",
      "Achieved 88.57% classification accuracy",
      "Implemented advanced preprocessing techniques",
      "Built robust deep learning model",
    ],
    startDate: "Jan 2024",
    endDate: "May 2024",
    status: "Completed",
    featured: true,
  },
  {
    id: "6",
    title: "Arambha Holidays",
    description: "Tourism booking platform with content management and payment support",
    longDescription:
      "Contributed to a tourism booking platform, implementing content updates, booking workflows, and payment integration support for seamless holiday booking experience.",
    category: "Full-Stack",
    image: "/images/projects/arambha-holidays.jpg",
    technologies: [
      { name: "Next.js", color: "bg-black" },
      { name: "React", color: "bg-cyan-500" },
      { name: "Node.js", color: "bg-green-500" },
      { name: "Payment Gateway", color: "bg-blue-600" },
      { name: "CMS", color: "bg-purple-500" },
    ],
    features: [
      "Tourism package booking system",
      "Content management system",
      "Payment gateway integration",
      "Booking workflow automation",
      "User-friendly interface",
      "Responsive design",
    ],
    challengesSolved: [
      "Implemented booking workflows",
      "Integrated payment gateway",
      "Built content management features",
      "Optimized user booking experience",
    ],
    liveDemo: "https://aarambhaholidays.com/",
    startDate: "Jun 2024",
    endDate: "Jul 2024",
    status: "Completed",
    featured: false,
  },
  {
    id: "7",
    title: "Movie Booking Ticket App",
    description: "Figma prototype with intuitive navigation, seat selection, and payment workflow",
    longDescription:
      "Designed an interactive movie booking prototype with intuitive navigation, seat selection functionality, and complete payment workflow using Figma.",
    category: "Frontend",
    image: "/images/projects/movie-booking.jpg",
    technologies: [
      { name: "Figma", color: "bg-purple-500" },
      { name: "UI/UX Design", color: "bg-pink-500" },
      { name: "Prototyping", color: "bg-blue-500" },
      { name: "Interaction Design", color: "bg-green-500" },
    ],
    features: [
      "Interactive Figma prototype",
      "Intuitive navigation flow",
      "Seat selection interface",
      "Payment workflow design",
      "User-centered design approach",
      "Mobile and desktop views",
    ],
    challengesSolved: [
      "Created seamless seat selection UX",
      "Designed intuitive navigation",
      "Built complete payment flow",
      "Ensured responsive design principles",
    ],
    startDate: "Jan 2024",
    endDate: "Feb 2024",
    status: "Completed",
    featured: false,
  },
  {
    id: "8",
    title: "Special Pumps - Industrial Pumps Portfolio",
    description: "Professional business portfolio website for industrial pump manufacturing company",
    longDescription:
      "Comprehensive business portfolio website for Special Pumps showcasing their industrial pump products, services, and company information. Built with Next.js for optimal performance and SEO.",
    category: "Full-Stack",
    image: "/images/projects/special-pumps.jpg",
    technologies: [
      { name: "Next.js", color: "bg-black" },
      { name: "React", color: "bg-cyan-500" },
      { name: "TypeScript", color: "bg-blue-600" },
      { name: "Tailwind CSS", color: "bg-cyan-400" },
    ],
    features: [
      "Professional product catalog",
      "Responsive business design",
      "SEO optimized",
      "Contact and inquiry forms",
      "Company profile section",
      "Mobile-friendly interface",
    ],
    challengesSolved: [
      "Created professional industrial website design",
      "Implemented product showcase system",
      "Optimized for search engines",
      "Built responsive layouts for all devices",
    ],
    liveDemo: "https://specialpumps.com/",
    startDate: "Aug 2024",
    endDate: "Sep 2024",
    status: "Completed",
    featured: true,
  },
  {
    id: "9",
    title: "Rotomech Dynamic - Business Portfolio",
    description: "Modern business portfolio website built with Next.js and TypeScript",
    longDescription:
      "Professional portfolio website for Rotomech Dynamic showcasing their industrial products and services. Built with Next.js (TSX) for performance, featuring modern UI/UX design and responsive layouts.",
    category: "Full-Stack",
    image: "/images/projects/rotomech.jpg",
    technologies: [
      { name: "Next.js (TSX)", color: "bg-black" },
      { name: "TypeScript", color: "bg-blue-600" },
      { name: "React", color: "bg-cyan-500" },
      { name: "Node.js", color: "bg-green-500" },
    ],
    features: [
      "Dynamic product showcase",
      "Modern UI/UX design",
      "Responsive across all devices",
      "Fast page load times",
      "Contact management system",
      "Professional branding",
    ],
    challengesSolved: [
      "Implemented modern design system",
      "Built scalable component architecture",
      "Optimized performance with Next.js",
      "Created professional business presence",
    ],
    liveDemo: "https://roto-dynamic-vw6c.onrender.com/",
    startDate: "Sep 2024",
    endDate: "Oct 2024",
    status: "Completed",
    featured: true,
  },
  {
    id: "10",
    title: "Task Manager - Full-Stack Mobile & Web App",
    description: "React Native mobile app with web version using MongoDB for task management",
    longDescription:
      "Complete task management solution with both mobile app (React Native) and web application. Features include task creation, assignment, tracking, and real-time updates using MongoDB for data persistence.",
    category: "Mobile",
    image: "/images/projects/task-manager.jpg",
    technologies: [
      { name: "React Native", color: "bg-cyan-500" },
      { name: "React", color: "bg-cyan-500" },
      { name: "MongoDB", color: "bg-green-600" },
      { name: "Node.js", color: "bg-green-500" },
      { name: "Express.js", color: "bg-gray-700" },
    ],
    features: [
      "Mobile and web applications",
      "Task creation and assignment",
      "Real-time task updates",
      "User authentication",
      "Task categorization and filtering",
      "Progress tracking",
    ],
    challengesSolved: [
      "Built cross-platform mobile app",
      "Synchronized data between mobile and web",
      "Implemented real-time updates",
      "Created unified user experience",
    ],
    startDate: "Oct 2024",
    endDate: "Nov 2024",
    status: "Completed",
    featured: false,
  },
  {
    id: "11",
    title: "PERN Task Product Dashboard",
    description: "Full-stack dashboard using PERN stack with Neon PostgreSQL and Arcjet security",
    longDescription:
      "Professional task and product management dashboard built with PERN stack (PostgreSQL, Express, React, Node). Uses Neon cloud database for PostgreSQL, Arcjet for security, and Next.js for the frontend.",
    category: "Full-Stack",
    image: "/images/projects/pern-dashboard.jpg",
    technologies: [
      { name: "PostgreSQL", color: "bg-blue-600" },
      { name: "Express.js", color: "bg-gray-700" },
      { name: "React", color: "bg-cyan-500" },
      { name: "Node.js", color: "bg-green-500" },
      { name: "Next.js", color: "bg-black" },
      { name: "Neon DB", color: "bg-green-400" },
      { name: "Arcjet", color: "bg-purple-600" },
    ],
    features: [
      "PERN stack architecture",
      "Neon PostgreSQL cloud database",
      "Arcjet security integration",
      "Task and product management",
      "Real-time analytics dashboard",
      "Secure authentication",
    ],
    challengesSolved: [
      "Integrated Neon cloud PostgreSQL",
      "Implemented Arcjet security layer",
      "Built comprehensive dashboard UI",
      "Optimized database queries",
    ],
    startDate: "Nov 2024",
    endDate: "Dec 2024",
    status: "Completed",
    featured: true,
  },
  {
    id: "12",
    title: "Sun Enterprise - Business Portfolio",
    description: "Professional business portfolio website showcasing company services and products",
    longDescription:
      "Modern business portfolio website for Sun Enterprise featuring company information, services, products, and contact capabilities. Built with Next.js for optimal performance and SEO.",
    category: "Full-Stack",
    image: "/images/projects/sun-enterprise.jpg",
    technologies: [
      { name: "Next.js", color: "bg-black" },
      { name: "React", color: "bg-cyan-500" },
      { name: "TypeScript", color: "bg-blue-600" },
      { name: "Tailwind CSS", color: "bg-cyan-400" },
    ],
    features: [
      "Professional business website",
      "Service and product showcase",
      "Responsive design",
      "Contact forms",
      "SEO optimized",
      "Fast loading times",
    ],
    challengesSolved: [
      "Created professional brand identity",
      "Implemented modern UI/UX",
      "Optimized for performance",
      "Built mobile-responsive layouts",
    ],
    liveDemo: "https://sun-enterprises.vercel.app/",
    startDate: "Nov 2024",
    endDate: "Dec 2024",
    status: "Completed",
    featured: false,
  },
  {
    id: "13",
    title: "Keerthana Tours and Travels",
    description: "Taxi booking and tours website with booking management system",
    longDescription:
      "Professional taxi and tours booking platform for Keerthana Tours and Travels. Features online booking, tour packages, taxi services, and customer management system.",
    category: "Full-Stack",
    image: "/images/projects/keerthana-tours.jpg",
    technologies: [
      { name: "Next.js", color: "bg-black" },
      { name: "React", color: "bg-cyan-500" },
      { name: "Node.js", color: "bg-green-500" },
      { name: "MongoDB", color: "bg-green-600" },
    ],
    features: [
      "Taxi booking system",
      "Tour package management",
      "Online reservation",
      "Customer management",
      "Pricing calculator",
      "Responsive design",
    ],
    challengesSolved: [
      "Built comprehensive booking system",
      "Implemented tour package management",
      "Created pricing calculation logic",
      "Optimized for mobile users",
    ],
    liveDemo: "https://keerthana-tours.onrender.com/",
    startDate: "Dec 2024",
    endDate: "Dec 2024",
    status: "Completed",
    featured: false,
  },
];

export const categories: ProjectCategory[] = [
  "Full-Stack",
  "Frontend",
  "Backend",
  "AI/ML",
  "Mobile",
];

export const technologyColors: Record<string, string> = {
  "Next.js": "bg-black",
  "Next.js (TSX)": "bg-black",
  React: "bg-cyan-500",
  "Node.js": "bg-green-500",
  Python: "bg-blue-500",
  MongoDB: "bg-green-600",
  PostgreSQL: "bg-blue-600",
  MySQL: "bg-blue-700",
  TailwindCSS: "bg-cyan-400",
  TypeScript: "bg-blue-600",
  Django: "bg-green-700",
  Flask: "bg-black",
  FastAPI: "bg-green-600",
  Docker: "bg-blue-500",
  AWS: "bg-orange-500",
  Firebase: "bg-yellow-500",
  "React Native": "bg-cyan-500",
  "Vue.js": "bg-green-500",
  Svelte: "bg-orange-600",
  Angular: "bg-red-600",
  Kafka: "bg-gray-700",
  ClickHouse: "bg-yellow-500",
  GitHub: "bg-gray-800",
  Figma: "bg-purple-500",
  MATLAB: "bg-orange-500",
};
